name: Sarif Report Generation and Upload
                                                                                                                                                                                                                                         
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
                                                                                                                                                                                                                                         
jobs:
  polaris-scan:
    runs-on: [mac-arm-sh]
                                                                                                                                                                                                                                         
    steps:
    
    - name: Checkout Source
      uses: actions/checkout@v4
                                                                                                                                                                                                                                         
    - name: Polaris Scan
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        polaris_assessment_types: "SCA,SAST"
        polaris_reports_sarif_create: true
        polaris_reports_sarif_severities: "CRITICAL"
        polaris_reports_sarif_groupSCAIssues: false
        polaris_reports_sarif_issue_types: "SAST,SCA"
        #detect_args: "--detect.source.path: ${{ github.workspace }}/nodejs-npm"

      
